name: Selenium Test Automation with Allure (No Cucumber)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Verify Chrome Installation
        run: |
          google-chrome --version
          which google-chrome

      # Option 1A: Exclude Cucumber runner classes by pattern
      - name: Run Selenium Tests Only (Exclude Cucumber)
        run: |
          mvn clean test -Dheadless=true -Dbrowser=chrome \
          -Dtest="!**/*TestRunner,!**/*Runner" \
          -DfailIfNoTests=false
        env:
          DISPLAY: :99

      - name: Generate Allure Report
        if: always()
        run: |
          mvn allure:report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-selenium-only
          path: target/allure-results/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-selenium-only
          path: target/site/allure-maven-plugin/
          retention-days: 30

      - name: Deploy Allure Report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin